import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/Navigation";
import { ReduxProvider } from "@/containers/ReduxProvider";
import AuthProvider from "@/containers/AuthProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
        {/* <body className={inter.className}> */}
          <AuthProvider>
            <Navigation>{children}</Navigation>
          </AuthProvider>
        </body>
      </ReduxProvider>
    </html>
  );
}
