import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Sidebar from "./components/sidebar/Sidebar";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <StoreProvider>
        <body className={`${inter.className}`}>
          <div className="flex flex-col min-h-screen">
            <Navbar title="Dashboard" />
            <div className="flex flex-1">
              <Sidebar />
              <main className="flex-1 p-4 mt-2 lg:ml-[240px] sm:ml-[240px] ml-0 bg-[#E6EFF5]">
                {children}
              </main>
            </div>
=======
      <body className={`${inter.className} h-full`}>
        <div className="flex flex-col min-h-screen">
          <Navbar title="Dashboard" />
          <div className="flex flex-1 ">
            <Sidebar />
            <main className="flex-1 p-4 lg:ml-[240px] sm:ml-[240px] ml-0 bg-[#F5F7FA] ">
              <div className="overflow-y-scroll">
                {children}
              </div>
            </main>
>>>>>>> 498b86e (Transaction page done)
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
