import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "../providers/StoreProvider";
import { AuthProvider } from "../providers/AuthProvider";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Banking Dashboard",
  description: "Generated by create next app",

}


export default function RootLayout({  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.svg" />
      </head>
      <AuthProvider>
        <StoreProvider>
          <body className={`${inter.className}`}>
            <div className="">
             <ToastContainer />
                <main className="">
                  {children}
                </main>
            </div>
          </body>
        </StoreProvider>
      </AuthProvider>
    </html>
  );
}
