// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "blog/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// ProfileUsecase is an autogenerated mock type for the ProfileUsecase type
type ProfileUsecase struct {
	mock.Mock
}

// CreateProfile provides a mock function with given fields: c, profile
func (_m *ProfileUsecase) CreateProfile(c context.Context, profile *domain.Profile) error {
	ret := _m.Called(c, profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Profile) error); ok {
		r0 = rf(c, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfile provides a mock function with given fields: c, id
func (_m *ProfileUsecase) DeleteProfile(c context.Context, id primitive.ObjectID) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProfileByID provides a mock function with given fields: c, id
func (_m *ProfileUsecase) GetProfileByID(c context.Context, id primitive.ObjectID) (*domain.ProfileResponse, error) {
	ret := _m.Called(c, id)

	var r0 *domain.ProfileResponse
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *domain.ProfileResponse); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfileResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: c, profile
func (_m *ProfileUsecase) UpdateProfile(c context.Context, profile *domain.Profile) error {
	ret := _m.Called(c, profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Profile) error); ok {
		r0 = rf(c, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProfileUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewProfileUsecase creates a new instance of ProfileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProfileUsecase(t mockConstructorTestingTNewProfileUsecase) *ProfileUsecase {
	mock := &ProfileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
