// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-full">
      <div className="w-1/5 border-r border-[#E6EFF5] hidden sm:block">
        <Sidebar />
      </div>

      <div className="flex-grow-1 flex flex-col w-full  sm:w-4/5">
        <Navbar title="Overviews" />

        <div className="bg-blue-100 ">
          {children}

        </div>

      </div>
      </body>
    </html>
    
  );
}
