import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import StoreProvider from "./StoreProvider";
import SessionWrapper from "./components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="scroll-smooth">
      <body className="h-screen overflow-hidden">
        
          <SessionWrapper>
            <StoreProvider>
              <LayoutWrapper>
                {children}
              </LayoutWrapper>
            </StoreProvider>  
          </SessionWrapper>
        
      
      </body>
    </html>
    
  );
}
