// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce/test/helpers/test_helper.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:convert' as _i23;
import 'dart:typed_data' as _i25;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecommerce/core/error/failures.dart' as _i14;
import 'package:ecommerce/core/platform/network_info.dart' as _i16;
import 'package:ecommerce/features/product/data/datasources/local_data_resource.dart'
    as _i17;
import 'package:ecommerce/features/product/data/datasources/remote_data_source.dart'
    as _i15;
import 'package:ecommerce/features/product/data/model/product_model.dart'
    as _i18;
import 'package:ecommerce/features/product/domain/entitity/product.dart' as _i3;
import 'package:ecommerce/features/product/domain/repositories/product_repository.dart'
    as _i5;
import 'package:ecommerce/features/product/domain/usecase/delete_product.dart'
    as _i9;
import 'package:ecommerce/features/product/domain/usecase/get_all_product.dart'
    as _i7;
import 'package:ecommerce/features/product/domain/usecase/get_product.dart'
    as _i6;
import 'package:ecommerce/features/product/domain/usecase/insert_product.dart'
    as _i10;
import 'package:ecommerce/features/product/domain/usecase/update_product.dart'
    as _i8;
import 'package:ecommerce/features/product/presentation/bloc/product_bloc.dart'
    as _i20;
import 'package:ecommerce/features/product/presentation/bloc/product_event.dart'
    as _i21;
import 'package:ecommerce/features/product/presentation/bloc/product_state.dart'
    as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i22;
import 'package:http/http.dart' as _i12;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;
import 'package:shared_preferences/shared_preferences.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_3 extends _i1.SmartFake
    implements _i4.AddressCheckResult {
  _FakeAddressCheckResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_4 extends _i1.SmartFake
    implements _i5.ProductRepository {
  _FakeProductRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductUsecase_5 extends _i1.SmartFake
    implements _i6.GetProductUsecase {
  _FakeGetProductUsecase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllProductUsecase_6 extends _i1.SmartFake
    implements _i7.GetAllProductUsecase {
  _FakeGetAllProductUsecase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateProductUsecase_7 extends _i1.SmartFake
    implements _i8.UpdateProductUsecase {
  _FakeUpdateProductUsecase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteProductUsecase_8 extends _i1.SmartFake
    implements _i9.DeleteProductUsecase {
  _FakeDeleteProductUsecase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertProductUsecase_9 extends _i1.SmartFake
    implements _i10.InsertProductUsecase {
  _FakeInsertProductUsecase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductState_10 extends _i1.SmartFake implements _i11.ProductState {
  _FakeProductState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_11 extends _i1.SmartFake implements _i12.Response {
  _FakeResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_12 extends _i1.SmartFake
    implements _i12.StreamedResponse {
  _FakeStreamedResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i5.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> getProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>> getAllProduct() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProduct,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>>.value(
                _FakeEither_0<_i14.Failure, List<_i3.Product>>(
          this,
          Invocation.method(
            #getAllProduct,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> insertProduct(
          _i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [product],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #insertProduct,
            [product],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> updateProduct(
          _i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #updateProduct,
            [product],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> deleteProduct(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i15.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.Product> getProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i13.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i13.Future<_i3.Product>);

  @override
  _i13.Future<List<_i3.Product>> getAllProduct() => (super.noSuchMethod(
        Invocation.method(
          #getAllProduct,
          [],
        ),
        returnValue: _i13.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i13.Future<List<_i3.Product>>);

  @override
  _i13.Future<_i3.Product> insertProduct(_i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [product],
        ),
        returnValue: _i13.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #insertProduct,
            [product],
          ),
        )),
      ) as _i13.Future<_i3.Product>);

  @override
  _i13.Future<_i3.Product> updateProduct(_i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i13.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #updateProduct,
            [product],
          ),
        )),
      ) as _i13.Future<_i3.Product>);

  @override
  _i13.Future<_i3.Product> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i13.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i13.Future<_i3.Product>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i16.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i17.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.Product> getLastProduct() => (super.noSuchMethod(
        Invocation.method(
          #getLastProduct,
          [],
        ),
        returnValue: _i13.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getLastProduct,
            [],
          ),
        )),
      ) as _i13.Future<_i3.Product>);

  @override
  _i13.Future<void> cacheProduct(_i18.ProductModel? productToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProduct,
          [productToCache],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i4.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i4.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i4.AddressCheckOptions>[],
      ) as List<_i4.AddressCheckOptions>);

  @override
  set addresses(List<_i4.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i4.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i13.Future<_i4.InternetConnectionStatus>.value(
            _i4.InternetConnectionStatus.connected),
      ) as _i13.Future<_i4.InternetConnectionStatus>);

  @override
  _i13.Stream<_i4.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i13.Stream<_i4.InternetConnectionStatus>.empty(),
      ) as _i13.Stream<_i4.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<_i4.AddressCheckResult> isHostReachable(
          _i4.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i13.Future<_i4.AddressCheckResult>.value(_FakeAddressCheckResult_3(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i13.Future<_i4.AddressCheckResult>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i19.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i13.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [GetProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductUsecase extends _i1.Mock implements _i6.GetProductUsecase {
  MockGetProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> execute(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);
}

/// A class which mocks [GetAllProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductUsecase extends _i1.Mock
    implements _i7.GetAllProductUsecase {
  MockGetAllProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>> execute(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>>.value(
                _FakeEither_0<_i14.Failure, List<_i3.Product>>(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, List<_i3.Product>>>);
}

/// A class which mocks [DeleteProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUsecase extends _i1.Mock
    implements _i9.DeleteProductUsecase {
  MockDeleteProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> execute(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);
}

/// A class which mocks [InsertProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertProductUsecase extends _i1.Mock
    implements _i10.InsertProductUsecase {
  MockInsertProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> execute(
          _i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [product],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #execute,
            [product],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);
}

/// A class which mocks [UpdateProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUsecase extends _i1.Mock
    implements _i8.UpdateProductUsecase {
  MockUpdateProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.Product>> execute(
          _i3.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [product],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>.value(
            _FakeEither_0<_i14.Failure, _i3.Product>(
          this,
          Invocation.method(
            #execute,
            [product],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.Product>>);
}

/// A class which mocks [ProductBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBloc extends _i1.Mock implements _i20.ProductBloc {
  MockProductBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetProductUsecase get getProductUsecase => (super.noSuchMethod(
        Invocation.getter(#getProductUsecase),
        returnValue: _FakeGetProductUsecase_5(
          this,
          Invocation.getter(#getProductUsecase),
        ),
      ) as _i6.GetProductUsecase);

  @override
  _i7.GetAllProductUsecase get getAllProductUsecase => (super.noSuchMethod(
        Invocation.getter(#getAllProductUsecase),
        returnValue: _FakeGetAllProductUsecase_6(
          this,
          Invocation.getter(#getAllProductUsecase),
        ),
      ) as _i7.GetAllProductUsecase);

  @override
  _i8.UpdateProductUsecase get updateProductUsecase => (super.noSuchMethod(
        Invocation.getter(#updateProductUsecase),
        returnValue: _FakeUpdateProductUsecase_7(
          this,
          Invocation.getter(#updateProductUsecase),
        ),
      ) as _i8.UpdateProductUsecase);

  @override
  _i9.DeleteProductUsecase get deleteProductUsecase => (super.noSuchMethod(
        Invocation.getter(#deleteProductUsecase),
        returnValue: _FakeDeleteProductUsecase_8(
          this,
          Invocation.getter(#deleteProductUsecase),
        ),
      ) as _i9.DeleteProductUsecase);

  @override
  _i10.InsertProductUsecase get insertProductUsecase => (super.noSuchMethod(
        Invocation.getter(#insertProductUsecase),
        returnValue: _FakeInsertProductUsecase_9(
          this,
          Invocation.getter(#insertProductUsecase),
        ),
      ) as _i10.InsertProductUsecase);

  @override
  _i11.ProductState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.ProductState);

  @override
  _i13.Stream<_i11.ProductState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i11.ProductState>.empty(),
      ) as _i13.Stream<_i11.ProductState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i21.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i21.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.ProductState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i21.ProductEvent>(
    _i22.EventHandler<E, _i11.ProductState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i21.ProductEvent, _i11.ProductState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i22.Change<_i11.ProductState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i12.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i12.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<_i12.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<_i12.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i23.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<_i12.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i23.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<_i12.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i23.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<_i12.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i23.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i12.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i12.Response>);

  @override
  _i13.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<String>.value(_i24.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Future<_i25.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i25.Uint8List>.value(_i25.Uint8List(0)),
      ) as _i13.Future<_i25.Uint8List>);

  @override
  _i13.Future<_i12.StreamedResponse> send(_i12.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i13.Future<_i12.StreamedResponse>.value(_FakeStreamedResponse_12(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i13.Future<_i12.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
