// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Claims is an autogenerated mock type for the Claims type
type Claims struct {
	mock.Mock
}

// GetSecretKey provides a mock function with given fields:
func (_m *Claims) GetSecretKey() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// SetExpiry provides a mock function with given fields:
func (_m *Claims) SetExpiry() {
	_m.Called()
}

// Valid provides a mock function with given fields:
func (_m *Claims) Valid() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClaims interface {
	mock.TestingT
	Cleanup(func())
}

// NewClaims creates a new instance of Claims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClaims(t mockConstructorTestingTNewClaims) *Claims {
	mock := &Claims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
