// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	domain "aait.backend.g10/domain"

	jwt "github.com/golang-jwt/jwt/v4"

	mock "github.com/stretchr/testify/mock"
)

// IJwtService is an autogenerated mock type for the IJwtService type
type IJwtService struct {
	mock.Mock
}

// CheckToken provides a mock function with given fields: authPart
func (_m *IJwtService) CheckToken(authPart string) (*jwt.Token, *domain.CustomError) {
	ret := _m.Called(authPart)

	if len(ret) == 0 {
		panic("no return value specified for CheckToken")
	}

	var r0 *jwt.Token
	var r1 *domain.CustomError
	if rf, ok := ret.Get(0).(func(string) (*jwt.Token, *domain.CustomError)); ok {
		return rf(authPart)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(authPart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *domain.CustomError); ok {
		r1 = rf(authPart)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.CustomError)
		}
	}

	return r0, r1
}

// FindClaim provides a mock function with given fields: token
func (_m *IJwtService) FindClaim(token *jwt.Token) (jwt.MapClaims, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for FindClaim")
	}

	var r0 jwt.MapClaims
	var r1 bool
	if rf, ok := ret.Get(0).(func(*jwt.Token) (jwt.MapClaims, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token) jwt.MapClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GenerateResetToken provides a mock function with given fields: email, code
func (_m *IJwtService) GenerateResetToken(email string, code int64) (string, *domain.CustomError) {
	ret := _m.Called(email, code)

	if len(ret) == 0 {
		panic("no return value specified for GenerateResetToken")
	}

	var r0 string
	var r1 *domain.CustomError
	if rf, ok := ret.Get(0).(func(string, int64) (string, *domain.CustomError)); ok {
		return rf(email, code)
	}
	if rf, ok := ret.Get(0).(func(string, int64) string); ok {
		r0 = rf(email, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, int64) *domain.CustomError); ok {
		r1 = rf(email, code)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.CustomError)
		}
	}

	return r0, r1
}

// GenerateToken provides a mock function with given fields: user
func (_m *IJwtService) GenerateToken(user *domain.User) (string, string, *domain.CustomError) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 string
	var r2 *domain.CustomError
	if rf, ok := ret.Get(0).(func(*domain.User) (string, string, *domain.CustomError)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) string); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*domain.User) *domain.CustomError); ok {
		r2 = rf(user)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*domain.CustomError)
		}
	}

	return r0, r1, r2
}

// ValidateToken provides a mock function with given fields: token
func (_m *IJwtService) ValidateToken(token string) (*jwt.Token, *domain.CustomError) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwt.Token
	var r1 *domain.CustomError
	if rf, ok := ret.Get(0).(func(string) (*jwt.Token, *domain.CustomError)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *domain.CustomError); ok {
		r1 = rf(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.CustomError)
		}
	}

	return r0, r1
}

// NewIJwtService creates a new instance of IJwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJwtService {
	mock := &IJwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
