import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import Header from "@/components/dashboard/header";
import Sidebar from "@/components/dashboard/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row h-screen`}>
        <Sidebar />
        <div className="flex flex-col w-full">
          <Header />
          <main className="flex-1 p-6 bg-slate-200 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}

