// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// VerifyEmail_Controller_interface is an autogenerated mock type for the VerifyEmail_Controller_interface type
type VerifyEmail_Controller_interface struct {
	mock.Mock
}

// SendVerificationEmail provides a mock function with given fields:
func (_m *VerifyEmail_Controller_interface) SendVerificationEmail() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// VerifyEmail provides a mock function with given fields:
func (_m *VerifyEmail_Controller_interface) VerifyEmail() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// NewVerifyEmail_Controller_interface creates a new instance of VerifyEmail_Controller_interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifyEmail_Controller_interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerifyEmail_Controller_interface {
	mock := &VerifyEmail_Controller_interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
