// Mocks generated by Mockito 5.4.4 from annotations
// in product_6/test/features/chat/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:product_6/core/error/failure.dart' as _i5;
import 'package:product_6/features/chat/domain/entities/chat_entity.dart'
    as _i6;
import 'package:product_6/features/chat/domain/entities/message_entity.dart'
    as _i7;
import 'package:product_6/features/chat/domain/repositories/chat_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>> initiateChat(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateChat,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.ChatEntity>(
          this,
          Invocation.method(
            #initiateChat,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.MessageEntity>>> getChatMessages(
          String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [chatId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.MessageEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.MessageEntity>>(
          this,
          Invocation.method(
            #getChatMessages,
            [chatId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.MessageEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>> myChatbyId(
          String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #myChatbyId,
          [chatId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.ChatEntity>(
          this,
          Invocation.method(
            #myChatbyId,
            [chatId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatEntity>>> myChat() =>
      (super.noSuchMethod(
        Invocation.method(
          #myChat,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ChatEntity>>(
          this,
          Invocation.method(
            #myChat,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteChat(String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteChat,
            [chatId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
