// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	domain "blogApp/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// BlogRepository is an autogenerated mock type for the BlogRepository type
type BlogRepository struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: ctx, comment
func (_m *BlogRepository) AddComment(ctx context.Context, comment *domain.Comment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Comment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddLike provides a mock function with given fields: ctx, like
func (_m *BlogRepository) AddLike(ctx context.Context, like *domain.Like) error {
	ret := _m.Called(ctx, like)

	if len(ret) == 0 {
		panic("no return value specified for AddLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Like) error); ok {
		r0 = rf(ctx, like)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddTagToBlog provides a mock function with given fields: ctx, blogID, tag
func (_m *BlogRepository) AddTagToBlog(ctx context.Context, blogID string, tag domain.BlogTag) error {
	ret := _m.Called(ctx, blogID, tag)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BlogTag) error); ok {
		r0 = rf(ctx, blogID, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddView provides a mock function with given fields: ctx, view
func (_m *BlogRepository) AddView(ctx context.Context, view *domain.View) error {
	ret := _m.Called(ctx, view)

	if len(ret) == 0 {
		panic("no return value specified for AddView")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.View) error); ok {
		r0 = rf(ctx, view)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBlog provides a mock function with given fields: ctx, blog
func (_m *BlogRepository) CreateBlog(ctx context.Context, blog *domain.Blog) error {
	ret := _m.Called(ctx, blog)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Blog) error); ok {
		r0 = rf(ctx, blog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTag provides a mock function with given fields: ctx, tag
func (_m *BlogRepository) CreateTag(ctx context.Context, tag *domain.BlogTag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlogTag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBlog provides a mock function with given fields: ctx, id
func (_m *BlogRepository) DeleteBlog(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, commentId
func (_m *BlogRepository) DeleteComment(ctx context.Context, commentId primitive.ObjectID) error {
	ret := _m.Called(ctx, commentId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, commentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTag provides a mock function with given fields: ctx, id
func (_m *BlogRepository) DeleteTag(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindBlogs provides a mock function with given fields: ctx, filter, page, pageSize, orderBy
func (_m *BlogRepository) FindBlogs(ctx context.Context, filter domain.BlogFilter, page int, pageSize int, orderBy []string) ([]*domain.GetBlogDTO, int, error) {
	ret := _m.Called(ctx, filter, page, pageSize, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for FindBlogs")
	}

	var r0 []*domain.GetBlogDTO
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlogFilter, int, int, []string) ([]*domain.GetBlogDTO, int, error)); ok {
		return rf(ctx, filter, page, pageSize, orderBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlogFilter, int, int, []string) []*domain.GetBlogDTO); ok {
		r0 = rf(ctx, filter, page, pageSize, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.GetBlogDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BlogFilter, int, int, []string) int); ok {
		r1 = rf(ctx, filter, page, pageSize, orderBy)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.BlogFilter, int, int, []string) error); ok {
		r2 = rf(ctx, filter, page, pageSize, orderBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAllBlogs provides a mock function with given fields: ctx
func (_m *BlogRepository) GetAllBlogs(ctx context.Context) ([]*domain.Blog, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBlogs")
	}

	var r0 []*domain.Blog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Blog, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Blog); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Blog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTags provides a mock function with given fields: ctx
func (_m *BlogRepository) GetAllTags(ctx context.Context) ([]*domain.BlogTag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 []*domain.BlogTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.BlogTag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.BlogTag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BlogTag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlogByID provides a mock function with given fields: ctx, id
func (_m *BlogRepository) GetBlogByID(ctx context.Context, id string) (*domain.GetSingleBlogDTO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlogByID")
	}

	var r0 *domain.GetSingleBlogDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.GetSingleBlogDTO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.GetSingleBlogDTO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetSingleBlogDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentById provides a mock function with given fields: ctx, commentId
func (_m *BlogRepository) GetCommentById(ctx context.Context, commentId string) (*domain.Comment, error) {
	ret := _m.Called(ctx, commentId)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentById")
	}

	var r0 *domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Comment, error)); ok {
		return rf(ctx, commentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Comment); ok {
		r0 = rf(ctx, commentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, commentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentsByBlogID provides a mock function with given fields: ctx, blogID
func (_m *BlogRepository) GetCommentsByBlogID(ctx context.Context, blogID string) ([]*domain.Comment, error) {
	ret := _m.Called(ctx, blogID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByBlogID")
	}

	var r0 []*domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Comment, error)); ok {
		return rf(ctx, blogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Comment); ok {
		r0 = rf(ctx, blogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLikeById provides a mock function with given fields: ctx, likeId
func (_m *BlogRepository) GetLikeById(ctx context.Context, likeId string) (*domain.Like, error) {
	ret := _m.Called(ctx, likeId)

	if len(ret) == 0 {
		panic("no return value specified for GetLikeById")
	}

	var r0 *domain.Like
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Like, error)); ok {
		return rf(ctx, likeId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Like); ok {
		r0 = rf(ctx, likeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Like)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, likeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLikesByBlogID provides a mock function with given fields: ctx, blogID
func (_m *BlogRepository) GetLikesByBlogID(ctx context.Context, blogID string) ([]*domain.Like, error) {
	ret := _m.Called(ctx, blogID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikesByBlogID")
	}

	var r0 []*domain.Like
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Like, error)); ok {
		return rf(ctx, blogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Like); ok {
		r0 = rf(ctx, blogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Like)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagByID provides a mock function with given fields: ctx, id
func (_m *BlogRepository) GetTagByID(ctx context.Context, id string) (*domain.BlogTag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTagByID")
	}

	var r0 *domain.BlogTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BlogTag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BlogTag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlogTag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetViewsByBlogID provides a mock function with given fields: ctx, blogID
func (_m *BlogRepository) GetViewsByBlogID(ctx context.Context, blogID string) ([]*domain.View, error) {
	ret := _m.Called(ctx, blogID)

	if len(ret) == 0 {
		panic("no return value specified for GetViewsByBlogID")
	}

	var r0 []*domain.View
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.View, error)); ok {
		return rf(ctx, blogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.View); ok {
		r0 = rf(ctx, blogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.View)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasUserLikedBlog provides a mock function with given fields: ctx, userId, blogId
func (_m *BlogRepository) HasUserLikedBlog(ctx context.Context, userId string, blogId string) (bool, error) {
	ret := _m.Called(ctx, userId, blogId)

	if len(ret) == 0 {
		panic("no return value specified for HasUserLikedBlog")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userId, blogId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userId, blogId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, blogId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasUserViewedBlog provides a mock function with given fields: ctx, userId, blogId
func (_m *BlogRepository) HasUserViewedBlog(ctx context.Context, userId string, blogId string) (bool, error) {
	ret := _m.Called(ctx, userId, blogId)

	if len(ret) == 0 {
		panic("no return value specified for HasUserViewedBlog")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userId, blogId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userId, blogId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, blogId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaginateBlogs provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *BlogRepository) PaginateBlogs(ctx context.Context, filter domain.BlogFilter, page int, pageSize int) ([]*domain.Blog, error) {
	ret := _m.Called(ctx, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for PaginateBlogs")
	}

	var r0 []*domain.Blog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlogFilter, int, int) ([]*domain.Blog, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BlogFilter, int, int) []*domain.Blog); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Blog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BlogFilter, int, int) error); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveLike provides a mock function with given fields: ctx, likeId
func (_m *BlogRepository) RemoveLike(ctx context.Context, likeId primitive.ObjectID) error {
	ret := _m.Called(ctx, likeId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, likeId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveTagFromBlog provides a mock function with given fields: ctx, blogID, tagID
func (_m *BlogRepository) RemoveTagFromBlog(ctx context.Context, blogID string, tagID string) error {
	ret := _m.Called(ctx, blogID, tagID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagFromBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, blogID, tagID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBlog provides a mock function with given fields: ctx, id, blog
func (_m *BlogRepository) UpdateBlog(ctx context.Context, id string, blog *domain.Blog) error {
	ret := _m.Called(ctx, id, blog)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Blog) error); ok {
		r0 = rf(ctx, id, blog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTag provides a mock function with given fields: ctx, id, tag
func (_m *BlogRepository) UpdateTag(ctx context.Context, id string, tag *domain.BlogTag) error {
	ret := _m.Called(ctx, id, tag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.BlogTag) error); ok {
		r0 = rf(ctx, id, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlogRepository creates a new instance of BlogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogRepository {
	mock := &BlogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
