import { TransactionProps } from "./ExpenseTable";

export const transactions: TransactionProps[] = [
  {
    transactionId: "#12548796",
    type: "shopping",
    senderUserName: "Spotify Subscription",
    description: "Spotify Subscriptionnhghghgh hnhjghjg",
    date: "28 Jan, 12:30 AM",
    amount: -2500,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "transfer",
    senderUserName: "Freepik Sales",
    description: "Freepik Sales",
    date: "25 Jan, 10:40 PM",
    amount: 750,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "service",
    senderUserName: "Mobile Service",
    description: "Mobile Service",
    date: "20 Jan, 10:40 PM",
    amount: -150,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "transfer",
    senderUserName: "Wilson",
    description: "Wilson",
    date: "15 Jan, 03:29 PM",
    amount: -1050,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "transfer",
    senderUserName: "Emilly",
    description: "Emilly",
    date: "14 Jan, 10:40 PM",
    amount: 840,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "transfer",
    senderUserName: "Emilly",
    description: "Emilly",
    date: "14 Jan, 10:40 PM",
    amount: 840,
    receiverUserName: "1234 ****",
  },
  {
    transactionId: "#12548796",
    type: "transfer",
    senderUserName: "Emilly",
    description: "Emilly",
    date: "14 Jan, 10:40 PM",
    amount: 840,
    receiverUserName: "1234 ****",
  },
];
