import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Layout/NavBar";
import Sidebar from "./components/Layout/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex ">
          <Sidebar/>
        <div className="w-full py-6 px-5">
          <NavBar/>
          {children}
        </div>
        </div>
        </body>
    </html>
  );
}
