package blog

import "errors"

var ErrUnableToCreateBlog = errors.New("unable to create blog")
var ErrUnableToUpdateBlog = errors.New("unable to update blog")
var ErrUnableToCreatComment = errors.New("unable to create comment")
var ErrInvalidID = errors.New("invalid ID")
var ErrUnableToDeleteBlog = errors.New("unable to delete blog")
var ErrBlogNotFound = errors.New("blog not found")
var ErrUnableToDeleteComment = errors.New("unable to delete comment")
var ErrCommentNotFound = errors.New("comment not found")
var ErrUnableToDislikeBlog = errors.New("unable to dislike blog")
var ErrUnableToLikeBlog = errors.New("unable to like blog")
var ErrUnableToUnLikeBlog = errors.New("unable to unlike blog")
var ErrUnableToUnDislikeBlog = errors.New("unable to undislike blog")
var ErrUnabletoGetBlog = errors.New("unable to get blog")
var ErrUnabletoSearchBlogs = errors.New("unable to search blogs")
var ErrUnableToGetComments = errors.New("unable to get comments")
var ErrUnableToGetComment = errors.New("unable to get comment")
var ErrUnabletoGetBlogs = errors.New("unable to get blogs")
var ErrLikeNotFound = errors.New("like not found")
var ErrDislikeNotFound = errors.New("dislike not found")
var ErrUnableToDeleteLikes = errors.New("unable to delete likes")
var ErrUnableToDeleteDislikes = errors.New("unable to delete dislikes")
var ErrUnableToDeleteComments = errors.New("unable to delete comments")
var ErrInvalidPopularityRange = errors.New("invalid popularity range")
var ErrAlreadyLiked = errors.New("already liked")
var ErrAlreadyDisliked = errors.New("already disliked")
var ErrNoLikeFound = errors.New("no like found")
var ErrNoDislikeFound = errors.New("no dislike found")
