import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import Sidebar from '@/components/SideBar/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex w-full bg-slate-100 min-h-screen font-Inter'>
          <div className='min-h-screen fixed left-0 top-0'>
            <Sidebar />
          </div>
          <div className='w-full overflow-hidden sm:ml-[210px] transaction-all duration-300'>
            <NavBar />
            <div className='p-5'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
