import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import Sidebar from '@/components/SideBar/Sidebar';
import StoreProvider from '@/providers/StoreProvider';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex w-full bg-slate-100 min-h-screen font-Inter'>
          <div className='min-h-screen fixed left-0 top-0 z-50'>
            <StoreProvider>
              <Sidebar />
            </StoreProvider>
          </div>
          <div className='w-full overflow-hidden sm:ml-[210px] transaction-all duration-300'>
            <StoreProvider>
              <NavBar />
            </StoreProvider>
            <div className='p-5 z-0'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
